### ISSUE TITLE
Make sure endpoint examples have `@DataRouteByExample` and add notes on what this means

### ISSUE THREAD

**Issue by nathandmoore** [BroadleafCommerce/MicroservicesConcepts#6]
[Original Help Scout ticket](https://secure.helpscout.net/conversation/2117845871/51084/)

**Comment by jefffischer** [comment]
When I was thinking about this, I also was hoping we could adjust the exception message from the routable datasource to be more informative. Since this is pretty much always because a route annotation is missing, instead of a confusing "null" message, something like "Unable to identify data route for flow. Did you forget to include a DataRouteByExample or DataRouteByKey annotation on an endpoint controller (or other flow entrypoint) to identify the data route for the flow? See [link] for more information."
